services:
  app.form.registration:
    class: UserBundle\Form\RegistrationType
    arguments: [%fos_user.model.user.class%]
    tags:
      - { name: form.type, alias: app_user_registration }

#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
